### ISSUE TITLE
Having trouble with sync with Silence Among Us Bot on build 2.8.4

### ISSUE THREAD

**Issue by rowennjohn** [denverquane/amonguscapture#119]
For some reason the bot is having trouble syncing with the Among us Capture every end of the round when returning to the lobby. We have to always restart the capture app and create a new room as a solution.

 This issue is not happening in version 2.7.10 at the moment it is the most stable version for Silence Among us Bot.

**Comment by varedz** [comment]
Hey there, sorry for the late response, the issue is with the bot itself not handling the data well. The capture was made for AutoMuteUs and if other bots interpret the data wrong then there's not much we can do. I would suggest switching over to the AutoMuteUs bot in order to gain the full potential of the AmongUsCapture.

**Comment by CarbonNeuron** [comment]
AutoMuteUs bot numbero uno!! 💯💯💯💯🏆🏆🏆💯💯💯💯🏆🏆🏆💯💯
