### ISSUE TITLE
Will it run on Mac using steamCMD and wine - uses a legitimate file of Among Us all contained on my computer

### ISSUE THREAD

**Issue by voxonbngu** [denverquane/amonguscapture#81]

**Comment by voxonbngu** [comment]
Sorry if this is the wrong place to ask, new to using GitHub

**Comment by sheldoncoupeheure** [comment]
Just try it ! If it doesn't work, you might want to use a Windows VM. I recommend Parallels Desktop (which I use and works flawlessly with Among Us) or VMWare (which I heard great things of).

**Comment by voxonbngu** [comment]
Gave it a try and it did not work haha, I've setup VMware and am just
waiting till my friends come on so i can see if it works. Thanks for your
support

**Comment by TauAkiou** [comment]
I had made an effort to try and run the capture on Wine before I started development on amonguscapture-gtk, and found that running it was extremely unreliable.

In order to get the capture to run, you need to install the .NET Core 3.1 runtime in your prefix. This should be all you need, but I started running into issues shortly after installation.

DirectX 11 should be supported on MacOS as of Wine 3.0, but YMMV under MacOS. You may need to try using MoltanVK to get it to work, with no guarantees.

If you happen to be able to get the game running reliably, it may be possible to write a ProcessMemoryMacos implementation, though I don't have access to a system running MacOS at this time.
